#!/bin/bash


# Set decoration geometry
berryc border_width       0
berryc inner_border_width 0
berryc title_height       10
berryc edge_gap           45 5 5 5
# Set decoration colors
berryc focus_color         eef3f5
berryc unfocus_color       cae2f2

berryc inner_focus_color   FFCB6B
berryc inner_unfocus_color 565679

berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc edge_lock   "true"
berryc set_font    terminus-12
